### PR TITLE
update IDB pages menu with data from S3

### PR DESCRIPTION
**Pull request by randyhoulahan**

### CODE REVIEW

**Comment by blaisefonseca** [comment]
I strongly advise to create a generic table to hold such values and use query to filter by need.

**Comment by blaisefonseca** [comment]
can you please merge 2019.1.x into master and start new release, its February?

**Comment by randyhoulahan** [comment]
> I strongly advise to create a generic table to hold such values and use query to filter by need.

As discussed this one will only change once a year.

**Comment by sbilodeau** [comment]
I agree it should not belong on s3. Why not just keep it int the project. Json OR html. It will also enable translations

**Pull request merged**
